"""initial migration and seeding

Revision ID: 7239e02f7850
Revises: ad6df61696c5
Create Date: 2024-03-27 13:22:48.778470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7239e02f7850'
down_revision = 'ad6df61696c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
